# Prometheus configuration for PhishNet Sandbox monitoring
global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "sandbox_alerts.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Sandbox Orchestrator
  - job_name: 'sandbox-orchestrator'
    static_configs:
      - targets: ['orchestrator:9090']
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # Sandbox Workers
  - job_name: 'sandbox-workers'
    static_configs:
      - targets: 
        - 'sandbox-worker-1:9090'
        - 'sandbox-worker-2:9090'
    metrics_path: /metrics
    scrape_interval: 10s
    scrape_timeout: 5s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: /metrics

  # Node exporter for system metrics
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']

  # Container metrics (cAdvisor)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
