apiVersion: v1
kind: Service
metadata:
  name: {{ include "phishnet.fullname" . }}-api
  labels:
    {{- include "phishnet.labels" . | nindent 4 }}
    app.kubernetes.io/component: api
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges:
    {{- with .Values.service.loadBalancerSourceRanges }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if and (eq .Values.service.type "ClusterIP") .Values.service.clusterIP }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if .Values.service.externalIPs }}
  externalIPs:
    {{- with .Values.service.externalIPs }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  {{- if .Values.service.sessionAffinity }}
  sessionAffinity: {{ .Values.service.sessionAffinity }}
  {{- end }}
  {{- if .Values.service.sessionAffinityConfig }}
  sessionAffinityConfig:
    {{- with .Values.service.sessionAffinityConfig }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.nodePort }}
      nodePort: {{ .Values.service.nodePort }}
      {{- end }}
    - port: {{ .Values.service.metricsPort }}
      targetPort: metrics
      protocol: TCP
      name: metrics
      {{- if and (or (eq .Values.service.type "NodePort") (eq .Values.service.type "LoadBalancer")) .Values.service.metricsNodePort }}
      nodePort: {{ .Values.service.metricsNodePort }}
      {{- end }}
  selector:
    {{- include "phishnet.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api

---
{{- if .Values.postgresql.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "phishnet.fullname" . }}-postgresql
  labels:
    {{- include "phishnet.labels" . | nindent 4 }}
    app.kubernetes.io/component: database
spec:
  type: ClusterIP
  ports:
    - port: 5432
      targetPort: postgresql
      protocol: TCP
      name: postgresql
  selector:
    {{- include "phishnet.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: database
{{- end }}

---
{{- if .Values.redis.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "phishnet.fullname" . }}-redis
  labels:
    {{- include "phishnet.labels" . | nindent 4 }}
    app.kubernetes.io/component: cache
spec:
  type: ClusterIP
  ports:
    - port: 6379
      targetPort: redis
      protocol: TCP
      name: redis
  selector:
    {{- include "phishnet.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: cache
{{- end }}

---
{{- if .Values.monitoring.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "phishnet.fullname" . }}-monitoring
  labels:
    {{- include "phishnet.labels" . | nindent 4 }}
    app.kubernetes.io/component: monitoring
  annotations:
    prometheus.io/scrape: "true"
    prometheus.io/port: "8001"
    prometheus.io/path: "/metrics"
spec:
  type: ClusterIP
  ports:
    - port: 8001
      targetPort: metrics
      protocol: TCP
      name: metrics
  selector:
    {{- include "phishnet.selectorLabels" . | nindent 4 }}
    app.kubernetes.io/component: api
{{- end }}
