services:
  - type: web
    name: phishnet-backend
    env: python
    region: oregon
    plan: free
    buildCommand: "pip install -r backend/requirements.txt"
    startCommand: "python backend/main.py"
    envVars:
      - key: PORT
        value: "$PORT"
      - key: ENVIRONMENT
        value: "production"
      - key: DATABASE_URL
        value: "postgresql://<USER>:<PASSWORD>@<HOST>:5432/<DB_NAME>"
      - key: REDIS_URL
        value: "redis://<REDIS_HOST>:6379/0"
      - key: SECRET_KEY
        value: "<REPLACE_WITH_STRONG_SECRET_KEY>"
      - key: GMAIL_CLIENT_ID
        value: "<GMAIL_CLIENT_ID>"
      - key: GMAIL_CLIENT_SECRET
        value: "<GMAIL_CLIENT_SECRET>"
      - key: GMAIL_REDIRECT_URI
        value: "https://<YOUR_RENDER_SERVICE_URL>/api/v1/auth/gmail/callback"
      - key: GOOGLE_CLOUD_PROJECT
        value: "<GCP_PROJECT_ID>"
      - key: AWS_REGION
        value: ""
      - key: AWS_SECRET_NAME
        value: ""
      - key: GCP_SECRET_NAME
        value: ""
      - key: VAULT_URL
        value: ""
      - key: VAULT_TOKEN
        value: ""
    healthCheckPath: "/health"
    autoDeploy: true
