services:
  # FastAPI Backend Web Service
  - type: web
    name: phishnet-api
    env: python
    plan: starter
    buildCommand: pip install -r requirements-production.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: ENVIRONMENT
        value: production
      - key: SECRET_KEY
        generateValue: true
      - key: JWT_SECRET_KEY
        generateValue: true
      - key: CORS_ORIGINS
        value: https://your-vercel-app.vercel.app,http://localhost:3000

  # PostgreSQL Database
  - type: pserv
    name: phishnet-db
    plan: starter
    databaseName: phishnet
    user: phishnet

  # Redis Cache
  - type: redis
    name: phishnet-redis
    plan: starter
