apiVersion: v2
name: phishnet
description: A comprehensive phishing detection and analysis platform
type: application
version: 1.0.0
appVersion: "1.0.0"
home: https://phishnet.example.com
sources:
  - https://github.com/example/phishnet
maintainers:
  - name: PhishNet Team
    email: team@phishnet.example.com
keywords:
  - phishing
  - security
  - email
  - threat-detection
dependencies:
  - name: postgresql
    version: "11.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: postgresql.enabled
  - name: redis
    version: "17.x.x"
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
  - name: prometheus
    version: "15.x.x"
    repository: https://prometheus-community.github.io/helm-charts
    condition: monitoring.prometheus.enabled
  - name: grafana
    version: "6.x.x"
    repository: https://grafana.github.io/helm-charts
    condition: monitoring.grafana.enabled
