replicaCount: 3
image:
  repository: phishnet/api
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 8000

resources:
  requests:
    cpu: 250m
    memory: 512Mi
  limits:
    cpu: 500m
    memory: 1Gi

monitoring:
  prometheus:
    enabled: true
    scrapeInterval: 15s
