apiVersion: apps/v1
kind: Deployment
metadata:
  name: phishnet-worker
  namespace: phishnet
  labels:
    app: phishnet-worker
spec:
  replicas: 2
  selector:
    matchLabels:
      app: phishnet-worker
  template:
    metadata:
      labels:
        app: phishnet-worker
    spec:
      containers:
      - name: phishnet-worker
        image: phishnet/worker:latest
        command: ["python", "-m", "worker.main"]
        env:
        - name: REDIS_URL
          valueFrom:
            secretKeyRef:
              name: phishnet-secrets
              key: redis-url
        resources:
          requests:
            memory: "256Mi"
            cpu: "100m"
          limits:
            memory: "512Mi"
            cpu: "200m"
