apiVersion: v1
kind: Secret
metadata:
  name: phishnet-secrets
  namespace: phishnet
  labels:
    app.kubernetes.io/name: phishnet
type: Opaque
stringData:
  # Database
  POSTGRES_PASSWORD: ""  # To be injected by external secret manager
  REDIS_PASSWORD: ""     # To be injected by external secret manager
  
  # Application
  SECRET_KEY: ""         # To be injected by external secret manager
  ENCRYPTION_KEY: ""     # To be injected by external secret manager
  WEBHOOK_SECRET: ""     # To be injected by external secret manager
  
  # Gmail Integration
  GMAIL_CLIENT_ID: ""    # To be injected by external secret manager
  GMAIL_CLIENT_SECRET: "" # To be injected by external secret manager
  
  # External APIs
  VIRUSTOTAL_API_KEY: "" # To be injected by external secret manager
  ABUSEIPDB_API_KEY: ""  # To be injected by external secret manager
  GEMINI_API_KEY: ""     # To be injected by external secret manager
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phishnet-config
  namespace: phishnet
  labels:
    app.kubernetes.io/name: phishnet
data:
  ENVIRONMENT: "production"
  LOG_LEVEL: "INFO"
  DATABASE_URL: "postgresql+asyncpg://phishnet_user:$(POSTGRES_PASSWORD)@postgres:5432/phishnet"
  REDIS_URL: "redis://:$(REDIS_PASSWORD)@redis:6379/0"
  BASE_URL: "https://phishnet.example.com"
  GMAIL_REDIRECT_URI: "https://phishnet.example.com/api/v1/auth/oauth/gmail/callback"
  WORKER_CONCURRENCY: "4"
  MAX_EMAIL_SIZE: "25MB"
  RATE_LIMIT_PER_MINUTE: "100"
  SESSION_TIMEOUT: "3600"
  JWT_EXPIRY: "86400"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: phishnet-monitoring-config
  namespace: phishnet
  labels:
    app.kubernetes.io/name: phishnet
    app.kubernetes.io/component: monitoring
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s
      evaluation_interval: 15s
    
    scrape_configs:
      - job_name: 'phishnet-api'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - phishnet
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: phishnet-api
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: metrics
      
      - job_name: 'phishnet-workers'
        kubernetes_sd_configs:
          - role: endpoints
            namespaces:
              names:
                - phishnet
        relabel_configs:
          - source_labels: [__meta_kubernetes_service_name]
            action: keep
            regex: phishnet-worker-.*
          - source_labels: [__meta_kubernetes_endpoint_port_name]
            action: keep
            regex: metrics
